### ISSUE TITLE
Layer and Head Selection for Attention

### ISSUE THREAD

**Issue by KKKKristen** [zlin7/ContextSL#1]
Dear Authors,

Thanks so much for the open-source project. I want to consult about if there is any file/code related to the layer&head selection for attention?

I noticed that in ```read_attn_loglikelihoods_all_next_token()```,  ```_get_attn_loglikelihoods_diskqueue()``` is called by passing ```all_heads=True```. In the paper you mentioned that using top10 heads are better than averaging attention over all heads. May I ask which part should I follow to derive the best attention configuration?

Thanks!

**Comment by zlin7** [comment]
Hi sorry for the late reply. Not sure if you figured out yourself, but the entry point is mostly https://github.com/zlin7/ContextSL/blob/44f37173ccaa89849d20683570d0b5d4e68f0a1e/pipeline/summ.py#L122. We feed the chosen heads [here](https://github.com/zlin7/ContextSL/blob/44f37173ccaa89849d20683570d0b5d4e68f0a1e/pipeline/summ.py#L180). Let me know if you have other questions!
